// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_BRLS1K65U0k2iwuuz2tcIgb4opnFls',
    appId: '1:737608519127:web:e3f0e334029b4838d04f92',
    messagingSenderId: '737608519127',
    projectId: 'onlineapp-71594',
    authDomain: 'onlineapp-71594.firebaseapp.com',
    storageBucket: 'onlineapp-71594.appspot.com',
    measurementId: 'G-5D6KDC55YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNpQD1UXlUHMc-7yCNGD7jqEhpE7j9pc',
    appId: '1:737608519127:android:413c7ede7316c890d04f92',
    messagingSenderId: '737608519127',
    projectId: 'onlineapp-71594',
    storageBucket: 'onlineapp-71594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPvsfNn8LKURMpcGV6YPfrkCY6MOYCbQ',
    appId: '1:737608519127:ios:89e681a871de01b6d04f92',
    messagingSenderId: '737608519127',
    projectId: 'onlineapp-71594',
    storageBucket: 'onlineapp-71594.appspot.com',
    iosBundleId: 'com.example.mrHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwPvsfNn8LKURMpcGV6YPfrkCY6MOYCbQ',
    appId: '1:737608519127:ios:89e681a871de01b6d04f92',
    messagingSenderId: '737608519127',
    projectId: 'onlineapp-71594',
    storageBucket: 'onlineapp-71594.appspot.com',
    iosBundleId: 'com.example.mrHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_BRLS1K65U0k2iwuuz2tcIgb4opnFls',
    appId: '1:737608519127:web:8dc97970fc422e20d04f92',
    messagingSenderId: '737608519127',
    projectId: 'onlineapp-71594',
    authDomain: 'onlineapp-71594.firebaseapp.com',
    storageBucket: 'onlineapp-71594.appspot.com',
    measurementId: 'G-XPJZCTRQ23',
  );
}
